ALTER TABLE users
ADD COLUMN IF NOT EXISTS gender VARCHAR(16) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS age INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS weight_kg DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS height_cm DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS resting_hr INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_hr INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS weekly_runs INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS threshold_pace_min_km DOUBLE PRECISION NOT NULL DEFAULT 0;