ALTER TABLE workouts
ADD COLUMN IF NOT EXISTS training_stress_score DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS intensity_factor DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS avg_stress SMALLINT,
ADD COLUMN IF NOT EXISTS sdrr_hrv SMALLINT,
ADD COLUMN IF NOT EXISTS rmssd_hrv SMALLINT;