ALTER TABLE users
DROP COLUMN IF EXISTS threshold_pace_min_km,
DROP COLUMN IF EXISTS weekly_runs,
DROP COLUMN IF EXISTS max_hr,
DROP COLUMN IF EXISTS resting_hr,
DROP COLUMN IF EXISTS height_cm,
DROP COLUMN IF EXISTS weight_kg,
DROP COLUMN IF EXISTS age,
DROP COLUMN IF EXISTS gender;